### ISSUE TITLE
步骤请教

### ISSUE THREAD

**Issue by GUESSZERO4** [BamLubi/Fabric.IoTAUT#1]
您好，请问有具体的部署步骤吗？

**Comment by BamLubi** [comment]
已完善README文件

**Comment by GUESSZERO4** [comment]
非常感谢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BamLubi/Fabric.IoTAUT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月24日(星期天) 晚上9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BamLubi/Fabric.IoTAUT] 步骤请教 (Issue #1)





 
已完善README文件
