### ISSUE TITLE
部署的问题

### ISSUE THREAD

**Issue by zjt0111** [BamLubi/Fabric.IoTAUT#2]
您好，在完成readme中各类步骤后未有报错，客户端页面仍显示无法连接区块链，不知是为何？

**Comment by BamLubi** [comment]
请在客户端页面打开开发者工具，在console一项中查看是否是CORS跨域问题。

**Comment by BamLubi** [comment]
如果是该问题，可以在浏览器插件市场安装`Cross Domain - CORS`插件，并将服务端ip地址添加到该插件中

**Comment by zjt0111** [comment]
非常感谢您的回答，能够解决接入的问题！
但是后续还遇到了鉴权问题无法解决
2022-05-14T10:20:27.787Z - error: [DiscoveryService]: send[mychannel] - Channel:mychannel received discovery error:access denied
Failed to evaluate transaction(query): Error: DiscoveryService: mychannel error: access denied
尝试多种方式暂无法解决，您若有空余时间可解答一二。

**Comment by zjt0111** [comment]
该问题已解决，参考https://stackoverflow.com/questions/57354414/hyperledger-fabric-error-mychannel-received-discovery-erroraccess-denied
删除iot-server/public/wallet里的所有文件
