### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by xiruo123** [BamLubi/Fabric.IoTAUT#4]
您好，我在按照您给别人解答的部署问题中，已经按照您的步骤将服务端IP添加进CROS插件中，但是还是会报CROS跨域问题，您能否有时间帮我i解答一下呢

**Comment by BamLubi** [comment]
使用插件形式解决CROS问题不是一个好的方案，可以自行百度其他方案。
给出下面几个参考博文：
- [s（vue解决跨域问题）blocked by CORS policy: Cross origin requests are only supported for protocol schemes](https://www.jianshu.com/p/111ca07b394f)
- [VUE CORS跨域问题 - 前端解决方案](https://blog.csdn.net/weixin_47687315/article/details/123349568)

**Comment by BamLubi** [comment]
如果有好的解决方案，可以提交pr

**Comment by xiruo123** [comment]
您好，我按照您给的这个第二个方法解决还是这个问题，是否和这个服务器无法访问有原因呢，这个IP地址同样也无法ping通。

**Comment by xiruo123** [comment]
您还，我按照您给的第二个方法进行解决，但是还是出现跨域问题，这个是否跟无法访问服务器端有关系呢，IP地址也是ping不同的。

**Comment by xiruo123** [comment]
或者我可以加您一个联系方式吗₍˄·͈༝·͈˄*₎◞ ̑̑，帮忙调试一下系统，有偿(/(°∞°)\)。

**Comment by BamLubi** [comment]
> 您还，我按照您给的第二个方法进行解决，但是还是出现跨域问题，这个是否跟无法访问服务器端有关系呢，IP地址也是ping不同的。

服务端首先需要保证能够访问，ip地址ping不通可以考虑：
- 服务端是否正常启用
- ip地址是否错误

前端只是个界面，用于访问后端提供的服务，可以脱离前端直接测试后端的服务（可以使用Postman工具）

**Comment by xiruo123** [comment]
我是按照您给的步骤一步一步做下来的，但还是连接不是区块链网络。希望您帮我解答一下，谢谢大哥！
